openprovider/Openprovider-WHMCS-domains

docs/custom_DNS_management_options.md
Clarifies how to add support for additional DNS record types
=> Documentation updates

modules/registrars/openprovider/configuration/additionalfields.php
add extra 2 fields to se domain registration 
https://openprovider.atlassian.net/browse/INTGRTNS-169
=> add extra 2 fields

modules/registrars/openprovider/OpenProvider/Logger.php
replace token with *
https://openprovider.atlassian.net/browse/INTGRTNS-172
=> replace token with *

CHANGELOG.md, modules/registrars/openprovider/OpenProvider/API/APIConfig.php
upgrade to  new version v-5.4 to v-5.5
=> add new version

includes/hooks/transliterate.php
add translator to show IPA characters 
https://openprovider.atlassian.net/browse/INTGRTNS-173
=> add translator to show IPA characters 

modules/registrars/openprovider/configuration/additionalfields.php
add additional fields to .it domain 
https://openprovider.atlassian.net/browse/INTGRTNS-54
=> add additional fields

modules/registrars/openprovider/init.php
fix auth issue 
https://github.com/openprovider/Openprovider-WHMCS-domains/pull/201
=> fix auth issue 

CHANGELOG.md, modules/registrars/openprovider/OpenProvider/API/APIConfig.php
upgrade to version 5.6 
- Allow end user to enter additional fields for domain .it(company registration number/vat number/social security number). 
- Enhanced module logs.
- Improved authentication performance.
- Improved language supportive with IPA(Phonetic) characters.
=> release 5.6

modules/registrars/openprovider/OpenProvider/API/Customer.php
https://openprovider.atlassian.net/browse/INTGRTNS-182
=> add table validation

modules/registrars/openprovider/init.php
change token valid time 
https://openprovider.atlassian.net/jira/people/557058%3A5b1fab9c-4935-4a67-964f-731f8ad8b9f1/boards/136?modal=detail&selectedIssue=INTGRTNS-183
=> change token time

CHANGELOG.md
=> chang log for 5.6

modules/registrars/openprovider/Controllers/System/ConfigController.php, modules/registrars/openprovider/helpers/Cache.php, modules/registrars/openprovider/init.php, modules/registrars/openprovider/openprovider.php
Added validation function(openprovider_config_validate) for user-given registrar configuration.
Validated the given configurations with the given environment(Sandbox or Production).
Reduced too many "generateAuthTokenRequest" requests invoking.
=> Intgrtns 204 implement the  config validate function

modules/registrars/openprovider/OpenProvider/API/ApiV1.php, modules/registrars/openprovider/vendor-static/guzzlehttp/psr7/src/Message.php, modules/registrars/openprovider/vendor-static/guzzlehttp/psr7/src/functions.php
Warnings are added into To-Do List in WHMCS
=> Intgrtns 206 openprovider api warnings should be displayed in whmcs

modules/registrars/openprovider/Controllers/System/ConfigController.php, modules/registrars/openprovider/OpenProvider/API/APIConfig.php
- Replace CTE text with Sandbox and it's link
- Change WHMCS module version
=> Replace CTE with Sandbox in the description of Test mode and change module version

modules/registrars/openprovider/Controllers/System/DomainController.php, modules/registrars/openprovider/Controllers/System/NameserverController.php, modules/registrars/openprovider/OpenProvider/API/APITools.php, modules/registrars/openprovider/OpenProvider/API/ApiHelper.php, modules/registrars/openprovider/OpenProvider/API/CommandMapping.php
Created a nameserver information getting method for Sandbox account configuration since "searchNsRequest" XML API does not work on Sandbox account configuration.
=> Intgrtns 212 xml parse issue when accepting the order for test mode

modules/registrars/openprovider/Controllers/System/ApiController.php, modules/registrars/openprovider/includes/templates/css/modules/dnssec.css, modules/registrars/openprovider/includes/templates/js/modules/dnssec.js
When the client clicks to activate DNSSEC and the domain has OP nameservers, then it generates a public key and gets into the DNSSEC page.
=> Intgrtns 219 dnssec activation when using our dns

modules/registrars/openprovider/OpenProvider/API/ApiHelper.php, modules/registrars/openprovider/OpenProvider/WhmcsHelpers/Domain.php
Reverted all changes developed for this task. Decided to put later versions and not for the next version.
=> Intgrtns 205 cron does not mark transferred out domains as canceled

CHANGELOG.md, modules/registrars/openprovider/Controllers/System/TldPricingController.php
- Change OP-WHMCS7 to Openprovider-WHMCS-domains in github links
=> Change OP-WHMCS7 from links and update to Openprovider-WHMCS-domains

modules/registrars/openprovider/OpenProvider/API/APITools.php
Fixed issue.
Previously, the user could create a domain with dummy nameservers (Ex: ns1.localhost).
Added new WHMCS side validation to validate provided nameservers to avoid passing dummy nameservers for domain registration.
=> INTGRTNS-258 WHMCS domain registration is created in rcp with dummy nameserver names if you do not have configured default nameservers

scripts/README.md, scripts/install_openprovider.sh, scripts/update_openprovider.sh
Created two bash scripts for installation and upgrade.
- install_openprovider.sh
- update_openprovider.sh
=> INTGRTNS-246 Simplify Openprovider WHMCS module installation and upgrade

README.md, scripts/README.md
- URL correction
- Curl silent mode
=> Update Scripts README.md

modules/registrars/openprovider/configuration/additionalfields.php
Adding dkAcceptance additional field from WHMCS side
=> Added .dk T&C Acceptance

modules/registrars/openprovider/configuration/additionalfields.php
Adding dkAcceptance additional field from WHMCS side
=> added .dk TC Acceptance

CHANGELOG.md, modules/registrars/openprovider/OpenProvider/API/APIConfig.php
Changed version for 5.8.1 release with .dk & .es registry changes
=> Version change and change log

modules/addons/openprovider/Controllers/Hooks/RenewHookController.php
This is already reviewed here for [branch 9.1](https://github.com/openprovider/Openprovider-WHMCS-domains/pull/357).
Merging this change to version-8.1 branch to release early
=> Fix error with Improper To-Do list creation for other registrar domains

CHANGELOG.md, README.md, modules/registrars/openprovider/OpenProvider/API/APIConfig.php
- Version correction
- Readme update
- Changelog update
=> Update version, readme and changelog

modules/registrars/openprovider/configuration/additionalfields.php, modules/registrars/openprovider/vendor-static/guzzlehttp/guzzle/src/BodySummarizer.php, modules/registrars/openprovider/vendor-static/guzzlehttp/psr7/src/Message.php, modules/registrars/openprovider/vendor-static/guzzlehttp/psr7/src/functions.php
- Re-enabled Entity Type field in additionalfields.php
- Added EU Country of Citizenship field with op_location and op_name mappings to additionalfields
=> Added missing additional field for .eu

modules/registrars/openprovider/vendor/openprovider/rest-client-php/src/Domain/Model/DomainAdditionalData.php
Update php-rest-client library locally to support consent_for_publishing in WHMCS
=> Update php-rest-client library locally to support consent_for_publishing

CHANGELOG.md, modules/registrars/openprovider/Controllers/Hooks/AdminAreaFooterController.php, modules/registrars/openprovider/Controllers/Hooks/AdminClientDomainsTabController.php, modules/registrars/openprovider/Controllers/System/DomainInformationController.php, modules/registrars/openprovider/OpenProvider/API/APIConfig.php, modules/registrars/openprovider/configuration/additionalfields.php, modules/registrars/openprovider/routes/hooks.php, modules/registrars/openprovider/vendor/openprovider/rest-client-php/src/Domain/Model/DomainAdditionalData.php
Added a Consent to Publish Domain Information checkbox for gTLDs in domain registration, transfer, and admin domain information modification pages – gTLDs now require explicit consent to publish contact details.
=> Version 8.4

CHANGELOG.md, modules/registrars/openprovider/OpenProvider/API/APIConfig.php, modules/registrars/openprovider/configuration/additionalfields.php
Added iisseAcceptance domainAdditionalData fro .se and .nu
=> Changes in .SE/NU Registration Flow
