openprovider/Openprovider-WHMCS-domains

- modules/registrars/openprovider/configuration/additionalfields.php
I think that the logical thing is that the .es are adapted to the real use in Spain, the best method is that it is translated as I indicate below. It works for me and it is easier for Spanish clients.
> Improve .es domains

- modules/registrars/openprovider/Models/Tld.php
Its my wrong
I accidentally inputted the type of the variable in the class. In php, variable types are not provided.
> [hotfix] remove variable type

- modules/registrars/openprovider/Controllers/System/ConfigController.php
- modules/registrars/openprovider/helpers/Cache.php
When browsing through the domain list as an admin, many Openprovider instances are launched. Each instance makes a request to Openprovider to validate the token. This cache reduces the amount of requests to just once per page load.
- Introduces single page load cache.
- Implements cache in the ConfigController.php -> checkRequest()
> Introducing a single request cache. Resolves #246

- modules/registrars/openprovider/classes/idna_convert.class.php
at four spots this class was still using the curly braces {}. These are now changed to [] to suit the php 8.1 requirements. Updated class does not break the WHMCS 8.6 update anymore.
> Updated curly braces to suit the php 8.1 requirements

- modules/addons/openprovider/resources/views/scheduled_domain_transfer/index.tpl
This template does not work in php 8.1 on whmcs 8.6.1.
Its a simple fix, check if the returned value is null before attempting to count it.
> Fix for error thrown by php 8.1 in whmcs 8.6.1

- modules/registrars/openprovider/OpenProvider/API/CustomerTags.php
count(): Argument #1 ($var) must be of type Countable|array, null given. Adjustments made to comply with php 8.1 coding.
Without this no domains can be registered.
> Type Countable Array in php 8.1 not valid coded

- modules/registrars/openprovider/Controllers/System/DomainSuggestionsController.php
'suggestTlds' in 'suggestionSettings' has a string value. To check whether the value is empty code used the count method which does not work with strings.
Changed the checker with empty method where we can pass a string value to it to check whether .suggestTlds. is empty.
> Fix bug in domain search in WHMCS client area

- modules/registrars/openprovider/OpenProvider/API/DomainRegistration.php
In OP side the initial autorenew value is set to Default, but in WHMCS code initial autorenew value is set as OFF.
Changed initial autorenew value from OFF to Default.
> Issue with autorenew value

- modules/registrars/openprovider/src/Handle.php
For any customer data change done in the WHMCS side caused customer contact handle duplication due to wrong object comparison. 
Fixed the wrong customer object comparison and removed isUsedByOtherDomains checker in findChanges method.
> Duplicate handles should not be created as a result of contact update

- modules/addons/openprovider/Controllers/System/SynchroniseController.php
Scheduled domain transfer syncing was not working by showing TypeError.
Avoided calling `count()` function for strings.
> Fixed for error thrown by Synchronise.php script

- modules/registrars/openprovider/Controllers/System/RenewDomainController.php
When renewing a domain which is in the WHMCS grace period state, it calls the wrong renewal API command.
So changed it to restoreDomain API command.
> Fix issue in grace period domain renewal API command

- modules/registrars/openprovider/vendor/wedevelopcoffee/wpower/src/Domain/AdditionalFields.php
There is case where whmcsField variable contains a string instead of an array, if in that case we need to check for the variable for an array and reassign an array with the string value in it.
> 'wedevelopcoffee' module seems to cause some PHP 8 errors

- modules/registrars/openprovider/OpenProvider/API/ApiHelper.php
- modules/registrars/openprovider/OpenProvider/WhmcsHelpers/Domain.php
A method to mark a domain as "canceled" if that domain is no longer available for that reseller account.
WHMCS native cron can be also used to sync this domain status.
> [Fixed] Cron does not mark transferred-out domains as canceled

- modules/addons/openprovider/Controllers/Hooks/RenewHookController.php
Fix for domain renewal error due to passing bool instead of an formatted array.
> Fix for domain renewal error

- modules/registrars/openprovider/Controllers/Hooks/AdminWidgetController.php
- modules/registrars/openprovider/Controllers/Hooks/Widgets/BalanceWidget.php
Fixed BalanceWidget closing issue in OP module.
Create a copying function for BalanceWidget in OP module.`(from OP-WHMCS7/modules/registrars/openprovider/Controllers/Hooks/Widgets/BalanceWidget.php to app/whmcs/modules/widgets/BalanceWidget.php)`
Added meaning full error messages when not having OP module.
> Fixed Openprovider balance widget closing issue.

- modules/registrars/openprovider/Controllers/System/EppController.php
- modules/registrars/openprovider/OpenProvider/API/ApiHelper.php
- modules/registrars/openprovider/OpenProvider/API/CommandMapping.php
Implement getEPPCode method and call getAuthCode API to get epp code for domains that do not return epp code with search domain request.
> Intgrtns 264 whmcs .es transfer auth code

- modules/registrars/openprovider/Controllers/Hooks/ClientAreaPrimarySidebarController.php
Fixed issue.
Previously, the DNSSEC management section is activated by default when registering a domain. Now it is not activated by default and needs to enable `DNS management` to activate DNSSEC management section.
> INTGRTNS-261 DNSSEC management section is activated by default when registering a domain

- modules/registrars/openprovider/Controllers/Hooks/DnsAuthController.php
To use the Openprovider **Single Domain DNS panel** page, the user needs to enable `"useNewDnsManagerFeature=true"` in the _**advanced-module-configurations.php**_ file.
Previously it was open in the same tab (redirect to Single Domain DNS panel page). Now it is able to open the Single Domain DNS panel page in new tab instead of redirecting.
> INTGRTNS-256 WHMCS feature request-open new dns manager in a new tab

- modules/addons/openprovider/Controllers/Hooks/RenewHookController.php
Previously it created todos' for all non-op domains with renewal_action == 'enable'.
Fix:-
When the domain is non-op with renewal_action == 'enable',
Only domains with **Scheduled Transfers with OP** needs to **create the todos**.
> Fix error with Improper To-Do list creation for other registrar domains

- modules/registrars/openprovider/vendor/phpdocumentor/reflection-docblock/src/DocBlock/Tags/InvalidTag.php
Changed to fix an exception with type error from the specific line
`TypeError: array_map(): Argument #2 ($array) must be of type array, null given`
> Fix error accessing admin dashboard

- modules/registrars/openprovider/init.php
- Replaced "[new Session()](https://github.com/openprovider/Openprovider-WHMCS-domains/blob/038200f3aa09aa9ef40f3f69cdeaf1c5067ea7f6/modules/registrars/openprovider/init.php#L65)" with "new Session(new MockArraySessionStorage())" inside [init.php](https://github.com/openprovider/Openprovider-WHMCS-domains/blob/038200f3aa09aa9ef40f3f69cdeaf1c5067ea7f6/modules/registrars/openprovider/init.php#L51).
- By calling new Session(), it silently runs session_start(). WHMCS therefore creates a second row in tblsessions that has no admin id; on the next refresh WHMCS sees that “guest” row as the most-recent session and forces a log-out.
- By replacing the new Session() call with new Session(new MockArraySessionStorage()), logouts can be eliminated.
- A MockArraySessionStorage backend keeps all …
> Fix for random admin logouts when using Openprovider with database sessions

- modules/registrars/openprovider/configuration/additionalfields.php
feat(whmcs/openprovider): add consentForPublishing to new gTLDs
- Add `consentForPublishing` tickbox to newly covered gTLDs in
modules/registrars/openprovider/configuration/additionalfields.php
- Default unchecked (privacy by default); label text polished for clarity
> Intgrtns 333 whmcs add consent for publishing parameter to g tl ds 
